### ISSUE TITLE
Unable to build on Arch Linux

### ISSUE THREAD

**Issue by lynix** [TNTwise/REAL-Video-Enhancer#87]
Before submitting an issue, please confirm it meets all the criteria
- [x] I am on a distribution that is at least Ubuntu 20.04+, this means that your distros packages are the same as, or more up to date than Ubuntu 20.04, Or using Windows 10/11.

**Describe the bug**
Build fails:

```
(...)
      source/bases/console.c: In function 'main':
      source/bases/console.c:77:14: error: implicit declaration of function '_PyMem_RawStrdup'; did you mean 'PyMem_RawFree'? [-Wimplicit-function-declaration]
         77 |     oldloc = _PyMem_RawStrdup(setlocale(LC_ALL, NULL));
            |              ^~~~~~~~~~~~~~~~
            |              PyMem_RawFree
      source/bases/console.c:77:12: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
         77 |     oldloc = _PyMem_RawStrdup(setlocale(LC_ALL, NULL));
            |            ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx-Freeze
Failed to build cx-Freeze

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (cx-Freeze)
```

**To Reproduce**
* clone repository
* execute `python3 build.py --build_exe`

**Expected behavior**
Software executable is being built.

**Screenshots**
n/a (error log given above)

**Logs**
n/a

**Desktop (please complete the following information):**
 - OS: Arch Linux (x86_64, up-to-date)
 
**GPU**
Intel i915 (does not matter as build fails).

**Additional context**
I'm happy to provide the full build log if that helps. I'm a C software developer but unfortunately don't know anything about Python.

**Comment by TNTwise** [comment]
Python3.13 isnt supported with the current deps. Please just use the pre release build right now.

**Comment by TNTwise** [comment]
Python3.13 won't be supported officially for the foreseeable future, please utilize something like pyenv to build with python 3.10
